# Generated by Django 5.2.6 on 2025-11-27 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("tarotistas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experiencia",
                    models.TextField(
                        help_text="Experiencia con el paciente y detalles de la consulta"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")],
                        default="abierto",
                        max_length=10,
                    ),
                ),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes",
                        to="citas.cita",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_paciente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarotista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="tarotistas.tarotista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-fecha_reporte"],
            },
        ),
    ]
