# Generated by Django 5.2.6 on 2025-12-21 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tarotistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(help_text='Número del día de la semana (0-6)')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('reservado', models.BooleanField(default=False)),
                ('tarotista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarotistas.tarotista')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
    ]
