# Generated by Django 5.2.6 on 2025-11-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apodo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
