# Generated by Django 5.2.6 on 2025-09-23 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarotista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia', models.IntegerField(help_text='Años de experiencia')),
                ('precio_por_sesion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(help_text='Bio profesional')),
                ('disponible', models.BooleanField(default=True)),
                ('calificacion', models.FloatField(default=0.0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarotista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
