# Generated by Django 5.2.6 on 2025-11-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12, null=True, unique=True),
        ),
    ]
